exclude:
  - "^ffs$"
  - "^aoa$"
  - "^brm$"
  - "^fixef$"
  - "^posterior_epred$"
  - "^background$"
  - "^spatSample$"
  - "^rasterize$"
  - "^predict$"
  - "^mess$"
  - "^NbClust$"
  - "^aggregate$"
  - "^project$"
  - "^mask$"
  - "^train$"