---
title: "Polygon Based Sampling"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Polygon Based Sampling}
  %\VignetteEngine{knitr::rmarkdown}, 
  %\VignetteEncoding{UTF-8}
description: >
  Sampling provisional seed transfer zones and ecoregions 
---

A variety of methods exist for implementing naive sampling schemes for polygon based products, such as provisional and empirical Seed Transfer Zones (pSTZs, and eSTZs), as well as Ecoregion (e.g. Omernik, or Baileys). 
The sampling of these products are all implemented using a single function in safeHavens `PolygonBasedSample` which has functionality to consider some environmental traits of the seed transfer zones, and size and number of polygon patches of both ecoregions and STZs. 

The function requires modes for two main scenarios - when a user wants **more** collections than zones exist in the data the function needs to use an 'increase' method. 
When a user wants **fewer** collections than zones exist a **decrease** method needs to be implemented. 
Three options are available for both scenarios. 
    1) Using the number of polygons per class
    2) using the total area of each class
    3) considering simple climate parameters for each class

Additionally, this function can be used on the cluster groups identified using the Isolation by Distance, Resistance, and Environmental workflows, when a user wants to decouple the clustering process from the number of samples. 

```{mermaid}
%%{init: {'theme':'dark', 'themeVariables': { 
    'primaryTextColor':'#000', 
    'lineColor':'#000', 
    'lineWidth':'24px',
    'fontSize':'20px', 
    'edgeSize':'20px',
    'fontFamily':'Arial'}}}%%

flowchart LR 
  A[No. of Collections <br> Requested]
  A ==> B[More collections<br> than zones<br> - Decrease]
  B ==> C{Total Area of pSTZ}
  C ==> D[Larger areas ++]
  C ==> E[Smaller areas ++]

  B ==> F{Count of pSTZ polygons}
  F ==> G[more polygons ++]
  F ==> H[fewer polygons ++]

  B ==> I{Climate of pSTZ}
  I ==> J[Warmer pSTZ ++]
  I ==> K[Drier pSTZ ++]

  A ==> L[Less collections<br> than zones <br> - Increase]

  L ==> M{Total Area of pSTZ}
  M ==> N[Largest n zones only]
  M ==> O[Smallest n zones only]

  L ==> P{Count of pSTZ polygons}
  P ==> Q[Most zones only]
  P ==> R[Fewest zones only]

  L ==> S{Climate of pSTZ}
  S ==> T[Warmer zones only]
  S ==> U[Drier zones only]

  %% Define color classes
  classDef requestedColor fill:#272AB0,color:#FFFFFF
  classDef areaColor fill:#9c2780,color:#000000
  classDef polygonColor fill:#57ACDC,color:#000000
  classDef climateColor fill:#E91E63,color:#000000
  classDef decisionColor fill:#60C689,color:#000000

  %% Apply classes to nodes
  class A requestedColor
  class C,M,D,E,N,O areaColor
  class F,P,G,H,Q,R polygonColor
  class I,S,J,K,T,U climateColor
  class B,L decisionColor
```

See `?PolygonBasedSample` for notes on implementation. 