// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_objective_sum
double calc_objective_sum(Rcpp::NumericMatrix dist, Rcpp::IntegerVector selected, double lambda_var);
RcppExport SEXP _safeHavens_calc_objective_sum(SEXP distSEXP, SEXP selectedSEXP, SEXP lambda_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type dist(distSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type selected(selectedSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_var(lambda_varSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_objective_sum(dist, selected, lambda_var));
    return rcpp_result_gen;
END_RCPP
}
// calc_objective_maxmin
double calc_objective_maxmin(Rcpp::NumericMatrix dist, Rcpp::IntegerVector selected);
RcppExport SEXP _safeHavens_calc_objective_maxmin(SEXP distSEXP, SEXP selectedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type dist(distSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type selected(selectedSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_objective_maxmin(dist, selected));
    return rcpp_result_gen;
END_RCPP
}
// local_search_swap
Rcpp::List local_search_swap(Rcpp::NumericMatrix dist, Rcpp::IntegerVector selected, Rcpp::IntegerVector candidates, std::string objective, int max_iter, double lambda_var);
RcppExport SEXP _safeHavens_local_search_swap(SEXP distSEXP, SEXP selectedSEXP, SEXP candidatesSEXP, SEXP objectiveSEXP, SEXP max_iterSEXP, SEXP lambda_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type dist(distSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type selected(selectedSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type candidates(candidatesSEXP);
    Rcpp::traits::input_parameter< std::string >::type objective(objectiveSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_var(lambda_varSEXP);
    rcpp_result_gen = Rcpp::wrap(local_search_swap(dist, selected, candidates, objective, max_iter, lambda_var));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_safeHavens_calc_objective_sum", (DL_FUNC) &_safeHavens_calc_objective_sum, 3},
    {"_safeHavens_calc_objective_maxmin", (DL_FUNC) &_safeHavens_calc_objective_maxmin, 2},
    {"_safeHavens_local_search_swap", (DL_FUNC) &_safeHavens_local_search_swap, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_safeHavens(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
