# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_objective_sum <- function(dist, selected, lambda_var = 0.0) {
    .Call('_safeHavens_calc_objective_sum', PACKAGE = 'safeHavens', dist, selected, lambda_var)
}

calc_objective_maxmin <- function(dist, selected) {
    .Call('_safeHavens_calc_objective_maxmin', PACKAGE = 'safeHavens', dist, selected)
}

local_search_swap <- function(dist, selected, candidates, objective, max_iter, lambda_var = 0.0) {
    .Call('_safeHavens_local_search_swap', PACKAGE = 'safeHavens', dist, selected, candidates, objective, max_iter, lambda_var)
}

