name: Update bayesian vignette
on:
  push:
    branches:
      - main
    paths:
      - 'vignettes/BayesianApproaches.Rmd'  # Only trigger when README.md changes
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Verify README exists
        run: ./run_bayes_vignette.sh
